SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].tbl_VoBoSolicitudesArchivos(
	[idArchivo] [int] IDENTITY(1,1) NOT NULL,
	Id_voBoSol [int] NOT NULL,
	[PlantillaArchivo] [varbinary](max) NOT NULL,
	[Nombre] [varchar](70) NOT NULL,
 CONSTRAINT [PK_PlantillaArchivo] PRIMARY KEY CLUSTERED 
(
	[idArchivo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO